version: '3.8'

services:


  db:
    extends:
      file: ./services/docker-compose-db.yml
      service: db

  backend:
    image: blockscout/blockscout:${DOCKER_TAG:-master}
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: 'blockscout'
    links:
      - db:database
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.chain1.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        ETHEREUM_JSONRPC_HTTP_URL: http://172.21.50.18:8545/
        INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'true'
        INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
        DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
        ECTO_USE_SSL: 'false'
        SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
        CHAIN_ID: '99999'
        API_V2_ENABLED: 'true'
        MIX_ENV: 'prod'
        ACCOUNT_ENABLED: 'false'
    ports:
      - 4000:4000
    volumes:
      - ./logs/:/app/logs/

  proxy_chain:
    extends:
      file: ./services/docker-compose-nginx.test.yml
      service: proxy